import React from "react";
import "./snackmachine.css";
import Ruler from "./Dialogs/Rular";

export default function SnackItems() {
  return (
    <div id="snack-collection">
      <Ruler />
      <ul>
        <li>
          <img
            src="https://pngimg.com/uploads/potato_chips/potato_chips_PNG79.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://pngimg.com/uploads/potato_chips/potato_chips_PNG79.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://pngimg.com/uploads/potato_chips/potato_chips_PNG79.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://pngimg.com/uploads/potato_chips/potato_chips_PNG79.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://pngimg.com/uploads/potato_chips/potato_chips_PNG79.png"
            class="snack"
          />
        </li>
      </ul>
      <hr />
      <ul>
        <li>
          <img
            src="https://www.pngitem.com/pimgs/m/433-4335544_jalapeno-kettle-chips-herrs-hd-png-download.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.pngitem.com/pimgs/m/433-4335544_jalapeno-kettle-chips-herrs-hd-png-download.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.pngitem.com/pimgs/m/433-4335544_jalapeno-kettle-chips-herrs-hd-png-download.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.pngitem.com/pimgs/m/433-4335544_jalapeno-kettle-chips-herrs-hd-png-download.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.pngitem.com/pimgs/m/433-4335544_jalapeno-kettle-chips-herrs-hd-png-download.png"
            class="snack"
          />
        </li>
      </ul>
      <hr />
      <ul>
        <li>
          <img
            src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=1229285-847&recipeName=680"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=1229285-847&recipeName=680"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=1229285-847&recipeName=680"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=1229285-847&recipeName=680"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&itemId=1229285-847&recipeName=680"
            class="snack"
          />
        </li>
      </ul>
      <hr />
      <ul>
        <li>
          <img
            src="https://assets.iceland.co.uk/i/iceland/Tuc_100g_Minis_Original_76212.jpg?$pdpzoom$"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://assets.iceland.co.uk/i/iceland/Tuc_100g_Minis_Original_76212.jpg?$pdpzoom$"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://assets.iceland.co.uk/i/iceland/Tuc_100g_Minis_Original_76212.jpg?$pdpzoom$"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://assets.iceland.co.uk/i/iceland/Tuc_100g_Minis_Original_76212.jpg?$pdpzoom$"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://assets.iceland.co.uk/i/iceland/Tuc_100g_Minis_Original_76212.jpg?$pdpzoom$"
            class="snack"
          />
        </li>
      </ul>
      <hr />
      <ul>
        <li>
          <img
            src="https://www.dropit.bm/wp-content/uploads/2019/05/Bagged_Snacks129.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.dropit.bm/wp-content/uploads/2019/05/Bagged_Snacks129.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.dropit.bm/wp-content/uploads/2019/05/Bagged_Snacks129.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.dropit.bm/wp-content/uploads/2019/05/Bagged_Snacks129.png"
            class="snack"
          />
        </li>
        <li>
          <img
            src="https://www.dropit.bm/wp-content/uploads/2019/05/Bagged_Snacks129.png"
            class="snack"
          />
        </li>
      </ul>
    </div>
  );
}
